In [1]:
import numpy as np

In [181]:
import cv2
import mediapipe as mp
import time
mpDraw = mp.solutions.drawing_utils
mpPose = mp.solutions.pose
pose = mpPose.Pose()
cap = cv2.VideoCapture('C:/Users/mi/YogaGuru/How to do Trikonasana - Triangle Pose.mp4')
count=0
landmark_frames_data=[]
while count<300:
    success, img = cap.read()
    h,w,c=img.shape 
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(imgRGB)
    landmark_frames_data.append({count:results.pose_landmarks})
    count+=1


In [183]:
 results.pose_landmarks.landmark

[x: 0.6347061
y: 0.48814774
z: -0.34277198
visibility: 0.9999993
, x: 0.64286494
y: 0.5027776
z: -0.34059626
visibility: 0.9999955
, x: 0.64279103
y: 0.50848097
z: -0.3406197
visibility: 0.99999774
, x: 0.64256597
y: 0.51495653
z: -0.34055722
visibility: 0.99999386
, x: 0.64298636
y: 0.49401492
z: -0.3328755
visibility: 0.99999636
, x: 0.64304906
y: 0.49272537
z: -0.3328504
visibility: 0.99999726
, x: 0.64317334
y: 0.49147737
z: -0.3327758
visibility: 0.9999944
, x: 0.6356797
y: 0.5428171
z: -0.29000598
visibility: 0.999996
, x: 0.636745
y: 0.51160705
z: -0.25253534
visibility: 0.9999972
, x: 0.6235042
y: 0.5016697
z: -0.32202002
visibility: 0.99999636
, x: 0.62422955
y: 0.49025175
z: -0.31155926
visibility: 0.99999756
, x: 0.5933317
y: 0.62327594
z: -0.20819151
visibility: 0.9999535
, x: 0.5914901
y: 0.4553261
z: -0.24050255
visibility: 0.99999875
, x: 0.61004335
y: 0.7597757
z: -0.24778421
visibility: 0.9946486
, x: 0.59889567
y: 0.31030452
z: -0.28333607
visibility: 0.99967545
, x: 

In [184]:
print(dir(results))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_asdict', '_field_defaults', '_fields', '_fields_defaults', '_make', '_replace', 'count', 'index', 'pose_landmarks', 'pose_world_landmarks']


In [185]:
import math
 
def getAngle(a, b, c):
    ang = math.degrees(math.atan2(c[1]-b[1], c[0]-b[0]) - math.atan2(a[1]-b[1], a[0]-b[0]))
    return ang + 360 if ang < 0 else ang
 
print(getAngle([0.23182656, 0.86334693, 0.00919855, 0.98291081], [0.2782656, 0.668, 0.00919855, 0.98291081], (0, 5)))

350.3028653420706


In [186]:
import numpy as np

In [187]:
results.pose_landmarks.landmark[0:3]

[x: 0.6347061
 y: 0.48814774
 z: -0.34277198
 visibility: 0.9999993,
 x: 0.64286494
 y: 0.5027776
 z: -0.34059626
 visibility: 0.9999955,
 x: 0.64279103
 y: 0.50848097
 z: -0.3406197
 visibility: 0.99999774]

In [188]:
test=[]
for res in results.pose_landmarks.landmark:
        test.append(np.array([res.x,res.y,res.z,res.visibility]))

In [189]:
test

[array([ 0.63470608,  0.48814774, -0.34277198,  0.99999928]),
 array([ 0.64286494,  0.50277758, -0.34059626,  0.99999553]),
 array([ 0.64279103,  0.50848097, -0.34061971,  0.99999774]),
 array([ 0.64256597,  0.51495653, -0.34055722,  0.99999386]),
 array([ 0.64298636,  0.49401492, -0.33287549,  0.99999636]),
 array([ 0.64304906,  0.49272537, -0.3328504 ,  0.99999726]),
 array([ 0.64317334,  0.49147737, -0.3327758 ,  0.9999944 ]),
 array([ 0.63567972,  0.54281712, -0.29000598,  0.99999601]),
 array([ 0.63674498,  0.51160705, -0.25253534,  0.9999972 ]),
 array([ 0.62350422,  0.5016697 , -0.32202002,  0.99999636]),
 array([ 0.62422955,  0.49025175, -0.31155926,  0.99999756]),
 array([ 0.59333169,  0.62327594, -0.20819151,  0.99995351]),
 array([ 0.59149009,  0.45532611, -0.24050255,  0.99999875]),
 array([ 0.61004335,  0.7597757 , -0.24778421,  0.99464858]),
 array([ 0.59889567,  0.31030452, -0.28333607,  0.99967545]),
 array([ 0.6291889 ,  0.87267911, -0.34149867,  0.96558762]),
 array([

In [190]:
test1=[]
for res in test:
    test1.append([res[0]*w,res[1]*h,res[2],res[3]])

In [191]:
h,w,c

(720, 1280, 3)

In [192]:
test1

[[812.4237823486328,
  351.46636962890625,
  -0.342771977186203,
  0.9999992847442627],
 [822.8671264648438,
  361.9998550415039,
  -0.3405962586402893,
  0.9999955296516418],
 [822.7725219726562,
  366.1062955856323,
  -0.3406197130680084,
  0.9999977350234985],
 [822.4844360351562,
  370.7687044143677,
  -0.3405572175979614,
  0.9999938607215881],
 [823.0225372314453,
  355.69074153900146,
  -0.33287549018859863,
  0.9999963641166687],
 [823.1027984619141,
  354.76226806640625,
  -0.3328503966331482,
  0.9999972581863403],
 [823.2618713378906,
  353.8637065887451,
  -0.3327758014202118,
  0.9999943971633911],
 [813.6700439453125, 390.8283233642578, -0.29000598192214966, 0.9999960064888],
 [815.0335693359375,
  368.35707664489746,
  -0.252535343170166,
  0.9999971985816956],
 [798.0854034423828, 361.202187538147, -0.322020024061203, 0.9999963641166687],
 [799.0138244628906,
  352.98125982284546,
  -0.31155925989151,
  0.9999975562095642],
 [759.4645690917969,
  448.7586736679077,
  -0

In [193]:
getAngle(test[0],test[1],test[2])    

209.8902613687352

In [194]:
getAngle(test1[0],test1[1],test1[2])

226.07354211635342

In [195]:
right_elbow_angle=getAngle(test1[16],test1[14],test1[12])
right_shoulder_angle=getAngle(test1[14],test1[12],test1[24])
left_shoulder_angle=getAngle(test1[13],test1[11],test1[23])
left_elbow_angle=getAngle(test1[15],test1[13],test1[11])


In [196]:
right_hip_angle=getAngle(test1[12],test1[24],test1[26])
left_hip_angle=getAngle(test1[11],test1[23],test1[25])
right_knee_angle=getAngle(test1[24],test1[26],test1[28])
left_knee_angle=getAngle(test1[23],test1[25],test1[27])


In [197]:
right_ankle_angle=getAngle(test1[26],test1[28],test1[32])
left_ankle_angle=getAngle(test1[25],test1[27],test1[31])
right_shoulder_wrt_nose_angle=getAngle(test1[0],test1[12],test1[11])
left_shoulder_wrt_nose_angle=getAngle(test1[0],test1[11],test1[12])


In [46]:
angles=[right_elbow_angle,
right_shoulder_angle,
left_shoulder_angle,
left_elbow_angle,
right_hip_angle,
left_hip_angle,
right_knee_angle,
left_knee_angle,
right_ankle_angle,
left_ankle_angle,
right_shoulder_wrt_nose_angle,
left_shoulder_wrt_nose_angle,
'MountainPose',
100]

In [204]:
angles1={'right_elbow_angle':right_elbow_angle,
'right_shoulder_angle':right_shoulder_angle,
'left_shoulder_angle':left_shoulder_angle,
'left_elbow_angle':left_elbow_angle,
'right_hip_angle':right_hip_angle,
'left_hip_angle':left_hip_angle,
'right_knee_angle':right_knee_angle,
'left_knee_angle':left_knee_angle,
'right_ankle_angle':right_ankle_angle,
'left_ankle_angle':left_ankle_angle,
'right_shoulder_wrt_nose_angle':right_shoulder_wrt_nose_angle,
'left_shoulder_wrt_nose_angle':left_shoulder_wrt_nose_angle,
'PoseName':'TrianglePose',
'PoseAccurracy':100}

In [205]:
PoseName='MountainPose'
PoseAccurracy=100

In [206]:
import pandas as pd
import numpy as np

In [200]:
column_list=['right_elbow_angle',
'right_shoulder_angle',
'left_shoulder_angle',
'left_elbow_angle',
'right_hip_angle',
'left_hip_angle',
'right_knee_angle',
'left_knee_angle',
'right_ankle_angle',
'left_ankle_angle',
'right_shoulder_wrt_nose_angle',
'left_shoulder_wrt_nose_angle',
'PoseName',
'PoseAccurracy']

In [207]:
data=pd.DataFrame(columns=column_list)

In [208]:
data=data.append(angles,ignore_index=True)

NameError: name 'angles' is not defined

In [209]:
data=data.append(angles1,ignore_index=True)

In [210]:
data

right_elbow_angle  right_shoulder_angle  left_shoulder_angle  \
0         176.548181            241.930561           106.435519   

   left_elbow_angle  right_hip_angle  left_hip_angle  right_knee_angle  \
0        184.497169       149.089999       48.132826        173.114715   

   left_knee_angle  right_ankle_angle  left_ankle_angle  \
0        172.61888         128.020588        153.977424   

   right_shoulder_wrt_nose_angle  left_shoulder_wrt_nose_angle      PoseName  \
0                      65.750732                    330.322414  TrianglePose   

  PoseAccurracy  
0           100

In [22]:
list(data.loc[1,:])[:-2]

NameError: name 'data' is not defined

In [ ]:
def get_error(ideal,practice):
        temp=[(abs(ideal[i]-practice[i])/ideal[i]) for i in range(12)]
       
        return 100-(sum(temp)*100/12) 
        

In [ ]:
get_error(list(data.loc[0,:])[:-2],list(data.loc[1,:])[:-2])

In [ ]:
data.iloc[1,13]=get_error(list(data.loc[0,:])[:-2],list(data.loc[1,:])[:-2])
data.iloc[2,13]=get_error(list(data.loc[0,:])[:-2],list(data.loc[2,:])[:-2])
data.iloc[3,13]=get_error(list(data.loc[0,:])[:-2],list(data.loc[3,:])[:-2])


In [23]:
get_error(list(data.loc[0,:])[:-2],list(data.loc[3,:])[:-2])

NameError: name 'get_error' is not defined

In [70]:
test[11]

array([ 0.59439504,  0.54103488, -0.1732163 ,  0.9998374 ])

In [71]:
test[12]

array([ 0.57379436,  0.37996355, -0.1076446 ,  0.99999213])

# Get data to dataframe

In [1]:
import math,numpy
 
def getAngle(a, b, c):
    ang = math.degrees(math.atan2(c[1]-b[1], c[0]-b[0]) - math.atan2(a[1]-b[1], a[0]-b[0]))
    return ang + 360 if ang < 0 else ang

In [4]:
%%time
import cv2
import mediapipe as mp
import time
mpDraw = mp.solutions.drawing_utils
mpPose = mp.solutions.pose
pose = mpPose.Pose()
#Enter your video location to collect the landmarks
cap = cv2.VideoCapture('C:/Users/mi/YogaGuru/Tree/10.jpg')
landmark_frames_data=[]
while True:
    success, img = cap.read()
    if success==True:
        h,w,c=img.shape 
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        results = pose.process(imgRGB)
        landmark_frames_data.append([results.pose_landmarks])
    else:
        break
cap.release() 

Wall time: 1.55 s


In [10]:
landmark_frames_data

[[landmark {
    x: 0.6072563
    y: 0.34515396
    z: -0.68290424
    visibility: 0.99979895
  }
  landmark {
    x: 0.6273069
    y: 0.33501476
    z: -0.6248688
    visibility: 0.99980336
  }
  landmark {
    x: 0.6411987
    y: 0.33513355
    z: -0.6251361
    visibility: 0.99963474
  }
  landmark {
    x: 0.65492326
    y: 0.33553743
    z: -0.62497413
    visibility: 0.99982053
  }
  landmark {
    x: 0.59299463
    y: 0.3351794
    z: -0.6050332
    visibility: 0.9998273
  }
  landmark {
    x: 0.58190167
    y: 0.3352522
    z: -0.60541743
    visibility: 0.9997092
  }
  landmark {
    x: 0.57133144
    y: 0.33527526
    z: -0.6056283
    visibility: 0.9998683
  }
  landmark {
    x: 0.67996687
    y: 0.34252626
    z: -0.3075774
    visibility: 0.9997832
  }
  landmark {
    x: 0.5605044
    y: 0.34188893
    z: -0.21103796
    visibility: 0.9999187
  }
  landmark {
    x: 0.6329125
    y: 0.35750446
    z: -0.5671288
    visibility: 0.9997876
  }
  landmark {
    x: 0.5888524

In [6]:
import pandas as pd
import numpy as np
column_list=['right_elbow_angle',
'right_shoulder_angle',
'left_shoulder_angle',
'left_elbow_angle',
'right_hip_angle',
'left_hip_angle',
'right_knee_angle',
'left_knee_angle',
'right_ankle_angle',
'left_ankle_angle',
'right_shoulder_wrt_nose_angle',
'left_shoulder_wrt_nose_angle',
'PoseName',
'PoseAccurracy']


In [11]:
def make_dict(data,pose_name):
    test=[]
    for res in data[0].landmark:
        test.append(np.array([res.x,res.y,res.z,res.visibility]))
    test1=[]
    for res in test:
        test1.append([res[0]*w,res[1]*h,res[2],res[3]])

    right_elbow_angle=getAngle(test1[16],test1[14],test1[12])
    right_shoulder_angle=getAngle(test1[14],test1[12],test1[24])
    left_shoulder_angle=getAngle(test1[13],test1[11],test1[23])
    left_elbow_angle=getAngle(test1[15],test1[13],test1[11])

    right_hip_angle=getAngle(test1[12],test1[24],test1[26])
    left_hip_angle=getAngle(test1[11],test1[23],test1[25])
    right_knee_angle=getAngle(test1[24],test1[26],test1[28])
    left_knee_angle=getAngle(test1[23],test1[25],test1[27])

    right_ankle_angle=getAngle(test1[26],test1[28],test1[32])
    left_ankle_angle=getAngle(test1[25],test1[27],test1[31])
    right_shoulder_wrt_nose_angle=getAngle(test1[0],test1[12],test1[11])
    left_shoulder_wrt_nose_angle=getAngle(test1[0],test1[11],test1[12])

    angles={'right_elbow_angle':right_elbow_angle,
    'right_shoulder_angle':right_shoulder_angle,
    'left_shoulder_angle':left_shoulder_angle,
    'left_elbow_angle':left_elbow_angle,
    'right_hip_angle':right_hip_angle,
    'left_hip_angle':left_hip_angle,
    'right_knee_angle':right_knee_angle,
    'left_knee_angle':left_knee_angle,
    'right_ankle_angle':right_ankle_angle,
    'left_ankle_angle':left_ankle_angle,
    'right_shoulder_wrt_nose_angle':right_shoulder_wrt_nose_angle,
    'left_shoulder_wrt_nose_angle':left_shoulder_wrt_nose_angle,
    'PoseName':pose_name,
    'PoseAccurracy':0}
    return angles

In [12]:
m=[]
def get_angles(landmark_frames_data,pose_name):
    for i in landmark_frames_data:
        if i[0]!=None:
            m.append(make_dict(i,pose_name))
       

In [13]:
get_angles(landmark_frames_data,'Tree')

In [14]:
# data=pd.DataFrame(columns=column_list)


In [15]:
data=data.append(m,ignore_index=True)

NameError: name 'data' is not defined

In [225]:
mylist

[152.02010001389226,
 204.04022363114063,
 162.5992908923049,
 205.90068050652118,
 235.163783674991,
 177.96154608711086,
 32.58321344384117,
 182.84257902790526,
 248.56670902922355,
 180.13175772451254,
 53.636357246675466,
 312.97552043913015,
 'Tree',
 100]

In [222]:
mylist=list(data.mean())

In [223]:
mylist.insert(-1,'Tree')

In [224]:
mylist[-1]=100

In [221]:
data['PoseAccurracy']=pd.to_numeric(data['PoseAccurracy'])

In [179]:
# data.to_csv('triangle.csv')

In [226]:
# data=pd.read_csv('triangle.csv')

In [143]:
# tree=data

In [226]:
tree.loc[0]=mylist

In [235]:
tree=tree.round(0)

In [237]:
tree

right_elbow_angle  right_shoulder_angle  left_shoulder_angle  \
0                152.0                 204.0                163.0   
1                317.0                 339.0                 26.0   
2                317.0                 339.0                 26.0   
3                318.0                 338.0                 26.0   
4                318.0                 338.0                 26.0   
..                 ...                   ...                  ...   
965              162.0                 179.0                195.0   
966              162.0                 179.0                195.0   
967              162.0                 179.0                196.0   
968              162.0                 179.0                196.0   
969              162.0                 179.0                196.0   

     left_elbow_angle  right_hip_angle  left_hip_angle  right_knee_angle  \
0               206.0            235.0           178.0              33.0   
1                50.0            246.0           178.0              26.0   
2                50.0            245.0           178.0              27.0   
3                50.0            245.0           178.0              27.0   
4                50.0            245.0           178.0              27.0   
..                ...              ...             ...               ...   
965             186.0            239.0           183.0              38.0   
966             186.0            239.0           183.0              38.0   
967             185.0            239.0           183.0              38.0   
968             185.0            239.0           183.0              38.0   
969             186.0            239.0           183.0              38.0   

     left_knee_angle  right_ankle_angle  left_ankle_angle  \
0              183.0              249.0             180.0   
1              181.0              248.0             178.0   
2              182.0              247.0             177.0   
3              182.0              247.0             176.0   
4              182.0              247.0             176.0   
..               ...                ...               ...   
965            179.0              243.0             188.0   
966            179.0              243.0             188.0   
967            179.0              243.0             188.0   
968            179.0              243.0             188.0   
969            179.0              243.0             188.0   

     right_shoulder_wrt_nose_angle  left_shoulder_wrt_nose_angle PoseName  \
0                             54.0                         313.0     Tree   
1                             53.0                         305.0     Tree   
2                             54.0                         305.0     Tree   
3                             54.0                         305.0     Tree   
4                             54.0                         305.0     Tree   
..                             ...                           ...      ...   
965                           58.0                         317.0     Tree   
966                           58.0                         317.0     Tree   
967                           59.0                         317.0     Tree   
968                           59.0                         317.0     Tree   
969                           59.0                         317.0     Tree   

     PoseAccurracy  
0            100.0  
1             69.0  
2             70.0  
3             70.0  
4             70.0  
..             ...  
965           93.0  
966           93.0  
967           93.0  
968           93.0  
969           93.0  

[970 rows x 14 columns]

In [229]:
def get_error(ideal,practice):
        temp=[(abs(ideal[i]-practice[i])/ideal[i]) for i in range(12)]
       
        return 100-(sum(temp)*100/12) 

In [230]:
for i in range(1,len(tree)):
    tree.iloc[i,13]=get_error(list(tree.loc[0,:])[:-2],list(tree.loc[i,:])[:-2])
    

In [233]:
# tree['PoseAccurracy']=pd.to_numeric(tree['PoseAccurracy'])

In [238]:
tree.to_csv('final_tree.csv')

In [162]:
data=warriordata

# Modelling

In [284]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [285]:
dataset

right_elbow_angle  right_shoulder_angle  left_shoulder_angle  \
0                 152.0                 204.0                163.0   
1                 317.0                 339.0                 26.0   
2                 317.0                 339.0                 26.0   
3                 318.0                 338.0                 26.0   
4                 318.0                 338.0                 26.0   
...                 ...                   ...                  ...   
4032              174.0                 258.0                 99.0   
4033              175.0                 258.0                 99.0   
4034              175.0                 258.0                 99.0   
4035              175.0                 258.0                 99.0   
4036              175.0                 258.0                 99.0   

      left_elbow_angle  right_hip_angle  left_hip_angle  right_knee_angle  \
0                206.0            235.0           178.0              33.0   
1                 50.0            246.0           178.0              26.0   
2                 50.0            245.0           178.0              27.0   
3                 50.0            245.0           178.0              27.0   
4                 50.0            245.0           178.0              27.0   
...                ...              ...             ...               ...   
4032             177.0            244.0           127.0             123.0   
4033             178.0            244.0           127.0             123.0   
4034             178.0            244.0           127.0             123.0   
4035             178.0            244.0           127.0             123.0   
4036             178.0            244.0           127.0             123.0   

      left_knee_angle  right_ankle_angle  left_ankle_angle  \
0               183.0              249.0             180.0   
1               181.0              248.0             178.0   
2               182.0              247.0             177.0   
3               182.0              247.0             176.0   
4               182.0              247.0             176.0   
...               ...                ...               ...   
4032            180.0              242.0             201.0   
4033            180.0              242.0             201.0   
4034            180.0              242.0             201.0   
4035            180.0              242.0             201.0   
4036            180.0              242.0             201.0   

      right_shoulder_wrt_nose_angle  left_shoulder_wrt_nose_angle  PoseName  \
0                              54.0                         313.0      Tree   
1                              53.0                         305.0      Tree   
2                              54.0                         305.0      Tree   
3                              54.0                         305.0      Tree   
4                              54.0                         305.0      Tree   
...                             ...                           ...       ...   
4032                           67.0                         326.0  Warrior2   
4033                           67.0                         326.0  Warrior2   
4034                           67.0                         326.0  Warrior2   
4035                           67.0                         326.0  Warrior2   
4036                           67.0                         326.0  Warrior2   

      PoseAccurracy  
0        100.000000  
1         69.000000  
2         70.000000  
3         70.000000  
4         70.000000  
...             ...  
4032      96.460701  
4033      96.553365  
4034      96.553365  
4035      96.553365  
4036      96.553365  

[4037 rows x 14 columns]

In [286]:
data=pd.get_dummies(dataset)

In [287]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [288]:
X_multi = data.drop("PoseAccurracy",axis=1)

In [289]:
y_multi = data['PoseAccurracy']

In [290]:
X_train,X_test,y_train,y_test = train_test_split(X_multi,y_multi,test_size=0.2)

In [291]:

list(X_multi.loc[1])

[317.0,
 339.0,
 26.0,
 50.0,
 246.0,
 178.0,
 26.0,
 181.0,
 248.0,
 178.0,
 53.0,
 305.0,
 0.0,
 1.0,
 0.0]

In [292]:
lm3 = LinearRegression()

In [293]:
lm3.fit(X_train, y_train)

LinearRegression()

In [294]:
y_predicted=lm3.predict(X_test)

In [295]:
from sklearn.metrics import mean_absolute_error

In [296]:
max(list(y_test-y_predicted))

2.9139466712654496

In [297]:
mean_absolute_error(y_test,y_predicted)

0.5991074063931467

In [298]:
from sklearn.metrics import r2_score

In [299]:
r2_score(y_test,y_predicted)

0.9834561600710441

# Adding data files and Forming Dataset


In [1]:
import pandas as pd

In [2]:
tree=pd.read_csv('final_tree.csv')
mountain=pd.read_csv('final_mountain.csv')
warrior2=pd.read_csv('final_warrior2.csv')

In [3]:
tree.drop("Unnamed: 0",axis=1,inplace=True)
mountain.drop("Unnamed: 0",axis=1,inplace=True)
warrior2.drop("Unnamed: 0",axis=1,inplace=True)

In [4]:
dataset=tree.append([mountain,warrior2],ignore_index=True)

In [5]:
dataset=dataset.round(0)

In [6]:
dataset

right_elbow_angle  right_shoulder_angle  left_shoulder_angle  \
0                 152.0                 204.0                163.0   
1                 317.0                 339.0                 26.0   
2                 317.0                 339.0                 26.0   
3                 318.0                 338.0                 26.0   
4                 318.0                 338.0                 26.0   
...                 ...                   ...                  ...   
4032              174.0                 258.0                 99.0   
4033              175.0                 258.0                 99.0   
4034              175.0                 258.0                 99.0   
4035              175.0                 258.0                 99.0   
4036              175.0                 258.0                 99.0   

      left_elbow_angle  right_hip_angle  left_hip_angle  right_knee_angle  \
0                206.0            235.0           178.0              33.0   
1                 50.0            246.0           178.0              26.0   
2                 50.0            245.0           178.0              27.0   
3                 50.0            245.0           178.0              27.0   
4                 50.0            245.0           178.0              27.0   
...                ...              ...             ...               ...   
4032             177.0            244.0           127.0             123.0   
4033             178.0            244.0           127.0             123.0   
4034             178.0            244.0           127.0             123.0   
4035             178.0            244.0           127.0             123.0   
4036             178.0            244.0           127.0             123.0   

      left_knee_angle  right_ankle_angle  left_ankle_angle  \
0               183.0              249.0             180.0   
1               181.0              248.0             178.0   
2               182.0              247.0             177.0   
3               182.0              247.0             176.0   
4               182.0              247.0             176.0   
...               ...                ...               ...   
4032            180.0              242.0             201.0   
4033            180.0              242.0             201.0   
4034            180.0              242.0             201.0   
4035            180.0              242.0             201.0   
4036            180.0              242.0             201.0   

      right_shoulder_wrt_nose_angle  left_shoulder_wrt_nose_angle  PoseName  \
0                              54.0                         313.0      Tree   
1                              53.0                         305.0      Tree   
2                              54.0                         305.0      Tree   
3                              54.0                         305.0      Tree   
4                              54.0                         305.0      Tree   
...                             ...                           ...       ...   
4032                           67.0                         326.0  Warrior2   
4033                           67.0                         326.0  Warrior2   
4034                           67.0                         326.0  Warrior2   
4035                           67.0                         326.0  Warrior2   
4036                           67.0                         326.0  Warrior2   

      PoseAccurracy  
0             100.0  
1              69.0  
2              70.0  
3              70.0  
4              70.0  
...             ...  
4032           96.0  
4033           97.0  
4034           97.0  
4035           97.0  
4036           97.0  

[4037 rows x 14 columns]

# making of function to get the angles


In [21]:
import math
import numpy as np
 
def getAngle(a, b, c):
    ang = math.degrees(math.atan2(c[1]-b[1], c[0]-b[0]) - math.atan2(a[1]-b[1], a[0]-b[0]))
    return round(ang + 360 if ang < 0 else ang)

In [22]:
def feature_list(poseLandmarks,posename):
    return [getAngle(poseLandmarks[16],poseLandmarks[14],poseLandmarks[12]),
    getAngle(poseLandmarks[14],poseLandmarks[12],poseLandmarks[24]),
    getAngle(poseLandmarks[13],poseLandmarks[11],poseLandmarks[23]),
    getAngle(poseLandmarks[15],poseLandmarks[13],poseLandmarks[11]),
    getAngle(poseLandmarks[12],poseLandmarks[24],poseLandmarks[26]),
    getAngle(poseLandmarks[11],poseLandmarks[23],poseLandmarks[25]),
    getAngle(poseLandmarks[24],poseLandmarks[26],poseLandmarks[28]),
    getAngle(poseLandmarks[23],poseLandmarks[25],poseLandmarks[27]),
    getAngle(poseLandmarks[26],poseLandmarks[28],poseLandmarks[32]),
    getAngle(poseLandmarks[25],poseLandmarks[27],poseLandmarks[31]),
    getAngle(poseLandmarks[0],poseLandmarks[12],poseLandmarks[11]),
    getAngle(poseLandmarks[0],poseLandmarks[11],poseLandmarks[12]),
    posename]

In [32]:
import pyttsx3
engine = pyttsx3.init()
def call():
    engine.say("Hello")
engine.runAndWait()
call()

In [23]:
lanmark_count=[]
def check_points(lm_count):
    global lanmark_count
    lanmark_count.append(lm_count)
    if len(lanmark_count)>100:
        print('not visible')
        call()
        lanmark_count.clear()
    else:
        pass
    
    
    

In [39]:
%%time
import cv2
import mediapipe as mp
import time
mpDraw = mp.solutions.drawing_utils
mpPose = mp.solutions.pose
pose = mpPose.Pose()
cap = cv2.VideoCapture(0)
while True:
    success, img = cap.read()
    if success==True:
        h,w,c=img.shape 
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        results = pose.process(imgRGB)
        
        poseLandmarks=[]
        if results.pose_landmarks:
            for lm in results.pose_landmarks.landmark:            
                poseLandmarks.append((int(lm.x*w),int(lm.y*h)))
#         print(feature_list(poseLandmarks,'pose1'))
        print(len(poseLandmarks))
        if len(poseLandmarks)==0:
            check_points(1)
            continue
        
        d=feature_list(poseLandmarks,1)
        print(load_model.predict(np.array(d).reshape(1, -1)))
        
    else:
        break
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

33
[67.4421806]
33
[67.65945805]
33
[67.93338123]
33
[68.01409726]
33
[68.03456319]
33
[67.93880825]
33
[67.89690422]
33
[68.0662886]
33
[68.03272056]
33
[67.90943819]
33
[67.86979361]
33
[67.84248972]
33
[67.72311356]
33
[67.90439866]
33
[67.9163058]
33
[68.08058166]
33
[67.99407797]
33
[67.99671651]
33
[68.00216865]
33
[67.9956239]
33
[68.05165808]
33
[68.0962516]
33
[68.01170243]
33
[67.84434523]
33
[67.86432306]
33
[67.86432306]
33
[67.95115876]
33
[67.84764215]
33
[67.91946338]
33
[67.96434147]
33
[67.96770584]
33
[68.01693593]
33
[68.1955219]
33
[68.24907126]


KeyboardInterrupt: 

In [41]:
cap.release()
cv2.destroyAllWindows()

In [16]:
import pickle
load_model=pickle.load(open('YogaGuru/YogaModel.pkl','rb'))

# creating pickel file

In [7]:
#{Tree:1,Mountain:2,Warrior2:3}
dataset['PoseName'].unique()

array(['Tree', 'Mountain', 'Warrior2'], dtype=object)

In [8]:
dataset.replace('Tree',1,inplace=True)
dataset.replace('Mountain',2,inplace=True)
dataset.replace('Warrior2',3,inplace=True)

In [9]:
dataset

right_elbow_angle  right_shoulder_angle  left_shoulder_angle  \
0                 152.0                 204.0                163.0   
1                 317.0                 339.0                 26.0   
2                 317.0                 339.0                 26.0   
3                 318.0                 338.0                 26.0   
4                 318.0                 338.0                 26.0   
...                 ...                   ...                  ...   
4032              174.0                 258.0                 99.0   
4033              175.0                 258.0                 99.0   
4034              175.0                 258.0                 99.0   
4035              175.0                 258.0                 99.0   
4036              175.0                 258.0                 99.0   

      left_elbow_angle  right_hip_angle  left_hip_angle  right_knee_angle  \
0                206.0            235.0           178.0              33.0   
1                 50.0            246.0           178.0              26.0   
2                 50.0            245.0           178.0              27.0   
3                 50.0            245.0           178.0              27.0   
4                 50.0            245.0           178.0              27.0   
...                ...              ...             ...               ...   
4032             177.0            244.0           127.0             123.0   
4033             178.0            244.0           127.0             123.0   
4034             178.0            244.0           127.0             123.0   
4035             178.0            244.0           127.0             123.0   
4036             178.0            244.0           127.0             123.0   

      left_knee_angle  right_ankle_angle  left_ankle_angle  \
0               183.0              249.0             180.0   
1               181.0              248.0             178.0   
2               182.0              247.0             177.0   
3               182.0              247.0             176.0   
4               182.0              247.0             176.0   
...               ...                ...               ...   
4032            180.0              242.0             201.0   
4033            180.0              242.0             201.0   
4034            180.0              242.0             201.0   
4035            180.0              242.0             201.0   
4036            180.0              242.0             201.0   

      right_shoulder_wrt_nose_angle  left_shoulder_wrt_nose_angle  PoseName  \
0                              54.0                         313.0         1   
1                              53.0                         305.0         1   
2                              54.0                         305.0         1   
3                              54.0                         305.0         1   
4                              54.0                         305.0         1   
...                             ...                           ...       ...   
4032                           67.0                         326.0         3   
4033                           67.0                         326.0         3   
4034                           67.0                         326.0         3   
4035                           67.0                         326.0         3   
4036                           67.0                         326.0         3   

      PoseAccurracy  
0             100.0  
1              69.0  
2              70.0  
3              70.0  
4              70.0  
...             ...  
4032           96.0  
4033           97.0  
4034           97.0  
4035           97.0  
4036           97.0  

[4037 rows x 14 columns]

In [10]:
# dataset.to_csv('yogadata.csv')

In [78]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score

In [79]:
X_multi = dataset.drop("PoseAccurracy",axis=1)
y_multi = dataset['PoseAccurracy']

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X_multi,y_multi,test_size=0.2)

In [81]:
model = LinearRegression()

In [82]:
model.fit(X_train, y_train)

LinearRegression()

In [83]:
y_predicted=model.predict(X_test)

In [84]:
mean_absolute_error(y_test,y_predicted)

0.6191865830181832

In [85]:
r2_score(y_test,y_predicted)

0.9787054120347481

In [86]:
import pickle 

In [87]:
pickle.dump(model,open('YogaModel.pkl','wb'))

In [96]:
d

[155, 180, 188, 199, 238, 181, 28, 179, 243, 184, 47, 317, 1]

In [95]:
model.predict(np.array(d).reshape(1, -1))

array([93.38079876])